
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  META_ARCHITECTURE: "OneFormer"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "/home/cpan14/datasets/checkpoints/oneformer/250_16_swin_l_oneformer_ade20k_160k.pth" # check
  SEM_SEG_HEAD:
    NAME: "OneFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 3 #check
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  ONE_FORMER:
    TRANSFORMER_DECODER_NAME: "ContrastiveMultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    CONTRASTIVE_WEIGHT: 0.5
    CONTRASTIVE_TEMPERATURE: 0.07
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 150 #check
    USE_TASK_NORM: True
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    CLASS_DEC_LAYERS: 2
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
  TEXT_ENCODER:
    WIDTH: 256
    CONTEXT_LENGTH: 77
    NUM_LAYERS: 6
    VOCAB_SIZE: 49408
    PROJ_NUM_LAYERS: 2
    N_CTX: 16
  TEST:
    SEMANTIC_ON: True # check
    INSTANCE_ON: False # True # FALSE # check
    PANOPTIC_ON: True # FALSE # check
    DETECTION_ON: False # check
    OVERLAP_THRESHOLD: 0.8
    OBJECT_MASK_THRESHOLD: 0.8
    TASK: "panoptic" # "semantic" #check
DATASETS:
  TRAIN: ("airbem_train",)
  TEST_PANOPTIC: ("airbem_val",)  # to evaluate instance and semantic performance as well
  TEST_INSTANCE: ("airbem_val",)
  TEST_SEMANTIC: ("airbem_val",)
SOLVER:
  IMS_PER_BATCH: 8 #check, per node, 8per node, 242 iters per epoch
  BASE_LR: 0.0001 #check
  STEPS: (21511, 23303) # (327778, 355092) #check, (24200 * (327778/368750), 24200 * (355092/368750))
  MAX_ITER: 24200 #368750 #check, 100 epoch (8bs)
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10 #check
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "airbem_semantic"
  MAX_SEQ_LEN: 77
  TASK_SEQ_LEN: 77
  TASK_PROB: 
    SEMANTIC: 0.33
    INSTANCE: 0.66
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 640) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 2560
  MAX_SIZE_TEST: 2560
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 640  # used in dataset mapper
TEST:
  EVAL_PERIOD: 1000 #5000, check
  DETECTIONS_PER_IMAGE: 150 # check
  AUG:
    ENABLED: False
    MIN_SIZES: [320, 480, 640, 800, 960, 1120]
    MAX_SIZE: 4480
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8 #4 #check
VERSION: 2
